---
- name: add docker repo key
  apt_key:
    keyserver=p80.pool.sks-keyservers.net
    id=58118E89F3A912897C070ADBF76221572C52609D

- name: add docker repo sources
  apt_repository:
    repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main'
    state=present
    update_cache=yes

- name: install docker
  apt:
    name=docker-engine
    state=latest
    update_cache=yes
    cache_valid_time=86400

- name: install pip
  apt:
    name=python-pip
    state=latest
    update_cache=yes
    cache_valid_time=86400

- name: install docker-py
  pip:
    name=docker-py
    state=latest
