---
- name: create collector textfile directory
  file:
    dest=/var/lib/node-exporter-textfile
    owner=ubuntu
    state=directory

- name: download node_exporter
  get_url:
    url=https://github.com/prometheus/node_exporter/releases/download/0.11.0/node_exporter-0.11.0.linux-amd64.tar.gz
    dest=/tmp
  register: new_archive

- name: unarchive node_exporter
  unarchive:
    src=/tmp/node_exporter-0.11.0.linux-amd64.tar.gz
    dest=/usr/local/bin
    owner=root
    group=root
    mode=0755
  when: new_archive|changed
  notify:
    - restart node_exporter

- name: configure node_exporter service conf
  template:
    dest=/etc/init/{{ item }}
    src={{ item }}.j2
    mode=0644
  with_items:
    - node_exporter.conf
  notify:
    - stop node_exporter
    - start node_exporter

- name: start service
  service:
    name=node_exporter
    state=started
